[package]
name = 'LeizdAptosTrove'
version = '0.1.0'
upgrade_policy = "compatible"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'devnet'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.LeizdAptosLib]
local = "../leizd-aptos-lib"

[dependencies.LeizdAptosCommon]
local = "../leizd-aptos-common"

[addresses]
leizd_aptos_trove="0x0123456789ABCDEF"
leizd_aptos_lib="0x0123456789ABCDEF"
leizd_aptos_common="0x0123456789ABCDEF"