---
profiles:
  default:
    private_key: "PRIVATE_KEY"
    public_key: "0xabfd71b17244ecadb2f54b0447defe0baa42a0c64fa054e2b3fa5f260530f717"
    account: bba4124e2d8de3f232431c695dc48d21b366941f142b11ed8327fa8660460043
    rest_url: "https://fullnode.devnet.aptoslabs.com/v1"
    faucet_url: "https://faucet.devnet.aptoslabs.com/"
