[package]
name = 'LeizdAptosLib'
version = '0.1.0'
upgrade_policy = "compatible"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'devnet'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
leizd_aptos_lib="0x0123456789ABCDEF"
std = "0x1"
