[package]
name = 'LeizdAptosCore'
version = '0.1.0'
upgrade_policy = "compatible"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'devnet'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.LeizdAptosLib]
local = "../leizd-aptos-lib"

[dependencies.LeizdAptosCommon]
local = "../leizd-aptos-common"

[dependencies.LeizdAptosTrove]
local = "../leizd-aptos-trove"

[dependencies.LeizdAptosCentralLiquidityPool]
local = "../leizd-aptos-central-liquidity-pool"

[dependencies.LeizdAptosLogic]
local = "../leizd-aptos-logic"

[dependencies.LeizdAptosExternal]
local = "../leizd-aptos-external"

[dependencies.LeizdAptosTreasury]
local = "../leizd-aptos-treasury"

[addresses]
leizd="0x0123456789ABCDEF"
leizd_aptos_lib="0x0123456789ABCDEF"
leizd_aptos_common="0x0123456789ABCDEF"
leizd_aptos_trove="0x0123456789ABCDEF"
leizd_aptos_central_liquidity_pool="0x0123456789ABCDEF"
leizd_aptos_logic="0x0123456789ABCDEF"
leizd_aptos_external="0x0123456789ABCDEF"
leizd_aptos_treasury="0x0123456789ABCDEF"
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
core_resources = "0xA550C18"
