[package]
name = 'LeizdAptosCore'
version = '0.1.0'
upgrade_policy = "compatible"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'devnet'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.Switchboard]
git = 'https://github.com/switchboard-xyz/aptos-sdk.git'
rev = 'main'
subdir = 'switchboard-move/switchboard'

[dependencies.LeizdAptosLib]
local = "../leizd-aptos-lib"

[dependencies.LeizdAptosCommon]
local = "../leizd-aptos-common"

[dependencies.LeizdAptosTrove]
local = "../leizd-aptos-trove"

[addresses]
leizd="0x0123456789ABCDEF"
leizd_aptos_lib="0x0123456789ABCDEF"
leizd_aptos_common="0x0123456789ABCDEF"
leizd_aptos_trove="0x0123456789ABCDEF"
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
core_resources = "0xA550C18"
switchboard = "0x14611263909398572be034debb2e61b6751cafbeaddd994b9a1250cb76b99d38"
