[package]
name = 'LeizdAptosTreasury'
version = '0.1.0'
upgrade_policy = "compatible"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'devnet'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.LeizdAptosCommon]
local = "../leizd-aptos-common"

[dependencies.LeizdAptosTrove]
local = "../leizd-aptos-trove"

[addresses]
leizd_aptos_treasury="0x0123456789ABCDEF"
leizd_aptos_common="0x0123456789ABCDEF"
leizd_aptos_trove="0x0123456789ABCDEF"
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
core_resources = "0xA550C18"
