[package]
name = 'LeizdAptosExternal'
version = '0.1.0'
upgrade_policy = "compatible"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'devnet'
subdir = 'aptos-move/framework/aptos-framework'

#[dependencies.Switchboard]
#git = 'https://github.com/switchboard-xyz/sbv2-aptos.git'
#rev = 'main'
#subdir = 'move/switchboard/'

[dependencies.LeizdAptosLib]
local = "../leizd-aptos-lib"

[dependencies.LeizdAptosCommon]
local = "../leizd-aptos-common"

[addresses]
leizd_aptos_external="0x0123456789ABCDEF"
leizd_aptos_lib="0x0123456789ABCDEF"
leizd_aptos_common="0x0123456789ABCDEF"
#switchboard = "0x34e2eead0aefbc3d0af13c0522be94b002658f4bef8e0740a21086d22236ad77" # devnet and testnet
#aptos_framework = "0x1"
