name: CD devnet
on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    env:
      TEST_PRIVATE_KEY: ${{ secrets.TEST_PRIVATE_KEY}}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Aptos
        uses: pontem-network/get-aptos@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true

      - name: Get Aptos
        uses: pontem-network/get-aptos@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true

      - name: aptos init
        run: sh new_account.sh

      - name: Set up release
        run: sh prerelease.sh

      - name: release leizd-aptos-common
        run: aptos move publish --package-dir leizd-aptos-common --override-size-check --assume-yes

      - name: release leizd-aptos-lib
        run: aptos move publish --package-dir leizd-aptos-lib --override-size-check --assume-yes

      - name: release leizd-aptos-external
        run: aptos move publish --package-dir leizd-aptos-external --override-size-check --assume-yes

      - name: release leizd-aptos-trove
        run: aptos move publish --package-dir leizd-aptos-trove --override-size-check --assume-yes

      - name: release leizd-aptos-treasury
        run: aptos move publish --package-dir leizd-aptos-treasury --override-size-check --assume-yes

      - name: release leizd-aptos-central-liquidity-pool
        run: aptos move publish --package-dir leizd-aptos-central-liquidity-pool --override-size-check --assume-yes

      - name: release leizd-aptos-logic
        run: aptos move publish --package-dir leizd-aptos-logic --override-size-check --assume-yes

      - name: release leizd-aptos-core
        run: aptos move publish --package-dir leizd-aptos-core --override-size-check --assume-yes --included-artifacts none

      - name: release leizd-aptos-entry
        run: aptos move publish --package-dir leizd-aptos-entry --override-size-check --assume-yes

      - name: Checkout test repo
        uses: actions/checkout@v3
        with:
          repository: horizonx-tech/leizd-aptos-test
          token: ${{ secrets.PERSONAL_TOKEN }}
          path: leizd-aptos-test
          ref: dev

      - name: push key file to test
        run: sh push_new_key_to_test.sh ${{ github.sha }}

      - name: Slack Notification on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_TITLE: Deploy Scucess
          SLACK_COLOR: good

      - name: Slack Notification on Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_TITLE: Deploy Failure
          SLACK_COLOR: danger
