name: CD devnet
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    env:
      TEST_PRIVATE_KEY: ${{ secrets.TEST_PRIVATE_KEY}}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Aptos
        uses: pontem-network/get-aptos@main
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up release
        run: sh prerelease.sh

      - name: release leizd-aptos-common
        run: aptos move publish --package-dir leizd-aptos-common --override-size-check

      - name: release leizd-aptos-lib
        run: aptos move publish --package-dir leizd-aptos-lib --override-size-check

      - name: release leizd-aptos-external
        run: aptos move publish --package-dir leizd-aptos-external --override-size-check

      - name: release leizd-aptos-trove
        run: aptos move publish --package-dir leizd-aptos-trove --override-size-check

      - name: release leizd-aptos-treasury
        run: aptos move publish --package-dir leizd-aptos-treasury --override-size-check

      - name: release leizd-aptos-core
        run: aptos move publish --package-dir leizd-aptos-core --override-size-check  --max-gas 100000

      - name: Slack Notification on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_TITLE: Deploy Scucess
          SLACK_COLOR: good

      - name: Slack Notification on Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_TITLE: Deploy Failure
          SLACK_COLOR: danger
