name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    name: CI
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Aptos
        uses: pontem-network/get-aptos@main
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile
        run: for pkg in `ls | grep leizd-aptos`; do aptos move compile --package-dir ${pkg} &; done

      - name: Test
        run: for pkg in `ls | grep leizd-aptos`; do aptos move test --package-dir ${pkg} &; done
